name: first-action
on: 
  push:
    branches:
      - main
jobs:
  test-github-action:
    name: test-github-action
    runs-on: ubuntu-20.04
    steps:
      - name: hello
        run: echo "hello"
      - name: goodbye
        run: echo "goodbye"
