name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install awscli --upgrade --user

    - name: Zip files
      run: zip -r website.zip .

    - name: Set AWS credentials from IAM Role
      run: aws configure set role_arn arn:aws:iam::184136210319:role/github-action && aws configure set credential_source Environment

    - name: Upload to S3
      run: aws s3 cp website.zip s3://testgit/
